import type { Department } from '../types/department';

export const mockDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Airport Operations',
    code: 'AOCC-OPS',
    headOfDepartment: 'Capt. Rajesh Sharma',
    contactExtension: '2451',
    location: 'AOCC Building & Airside',
    totalExtensions: 28,
    totalCalls: 5840,
    totalDurationHours: 920,
    billableCalls: 4320,
    monthlyCost: 118400,
    status: 'Active',
    budgetAllocation: 150000,
  },
  {
    id: 'dept-2',
    name: 'Security & Compliance',
    code: 'SEC-Corporate Security',
    headOfDepartment: 'Col. Vikramaditya Rathore',
    contactExtension: '3187',
    location: 'All Terminals & Perimeter Gates',
    totalExtensions: 34,
    totalCalls: 4620,
    totalDurationHours: 740,
    billableCalls: 3100,
    monthlyCost: 92600,
    status: 'Active',
    budgetAllocation: 120000,
  },
  {
    id: 'dept-3',
    name: 'Engineering & Maint',
    code: 'ENG-MAIN',
    headOfDepartment: 'Er. Sanjay Verma',
    contactExtension: '4212',
    location: 'Technical Complex & Substations',
    totalExtensions: 22,
    totalCalls: 3450,
    totalDurationHours: 510,
    billableCalls: 2480,
    monthlyCost: 67200,
    status: 'Active',
    budgetAllocation: 90000,
  },
  {
    id: 'dept-4',
    name: 'Customer Service',
    code: 'CUST-SERV',
    headOfDepartment: 'Ms. Pooja Nair',
    contactExtension: '5020',
    location: 'Terminal 1, 2 & 3 Information Desks',
    totalExtensions: 18,
    totalCalls: 3280,
    totalDurationHours: 480,
    billableCalls: 2150,
    monthlyCost: 58900,
    status: 'Active',
    budgetAllocation: 75000,
  },
  {
    id: 'dept-5',
    name: 'Cargo Operations',
    code: 'CRG-LOG',
    headOfDepartment: 'Mr. Amitabh Sen',
    contactExtension: '2105',
    location: 'Cargo Terminal Complex',
    totalExtensions: 16,
    totalCalls: 2740,
    totalDurationHours: 410,
    billableCalls: 2210,
    monthlyCost: 52400,
    status: 'Active',
    budgetAllocation: 70000,
  },
  {
    id: 'dept-6',
    name: 'IT & Telecom',
    code: 'IT-COMM',
    headOfDepartment: 'Mr. Alok Mishra',
    contactExtension: '6011',
    location: 'Datacenter & Server Facility',
    totalExtensions: 14,
    totalCalls: 1980,
    totalDurationHours: 320,
    billableCalls: 1320,
    monthlyCost: 41200,
    status: 'Active',
    budgetAllocation: 60000,
  },
  {
    id: 'dept-7',
    name: 'Administration',
    code: 'ADM-GEN',
    headOfDepartment: 'Dr. Vivek Mehra',
    contactExtension: '1102',
    location: 'Airport Authority Admin Block',
    totalExtensions: 12,
    totalCalls: 1640,
    totalDurationHours: 260,
    billableCalls: 1410,
    monthlyCost: 32540,
    status: 'Active',
    budgetAllocation: 50000,
  },
  {
    id: 'dept-8',
    name: 'Finance & Accounts',
    code: 'FIN-ACC',
    headOfDepartment: 'Mrs. Kavita Sundaram',
    contactExtension: '7025',
    location: 'Admin Building, 1st Floor',
    totalExtensions: 10,
    totalCalls: 1306,
    totalDurationHours: 202,
    billableCalls: 935,
    monthlyCost: 23000,
    status: 'Active',
    budgetAllocation: 40000,
  },
];
