import type { User } from '../types/user';
import type { SystemSettings } from '../types/settings';

export const mockUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Vikas Telecom Admin',
    employeeId: 'ADM-001',
    email: 'telecom.admin@airport.gov.in',
    department: 'IT',
    role: 'Administrator',
    extension: '6011',
    location: 'Central Control Tower',
    deviceModel: 'Cisco IP Phone 8865',
    monthlyCalls: 342,
    monthlyCost: 1420.50,
    status: 'Active',
    lastLogin: '2026-09-11 11:15:00',
  },
  {
    id: 'usr-2',
    name: 'Rahul Sharma',
    employeeId: 'EMP-OPS-10231',
    email: 'rahul.sharma@airport.gov.in',
    department: 'Airport Operations',
    role: 'Department Manager',
    extension: '2451',
    location: 'Terminal 3 — Ops Office',
    deviceModel: 'Cisco IP Phone 8845',
    monthlyCalls: 148,
    monthlyCost: 736.91,
    status: 'Active',
    lastLogin: '2026-09-11 10:45:00',
  },
  {
    id: 'usr-3',
    name: 'Amit Kumar',
    employeeId: 'EMP-SEC-10245',
    email: 'amit.kumar@airport.gov.in',
    department: 'Security',
    role: 'Department Manager',
    extension: '2231',
    location: 'Terminal 1 — Security Post 4',
    deviceModel: 'Cisco IP Phone 7841',
    monthlyCalls: 126,
    monthlyCost: 604.40,
    status: 'Active',
    lastLogin: '2026-09-11 09:30:00',
  },
  {
    id: 'usr-4',
    name: 'Priya Singh',
    employeeId: 'EMP-IT-10267',
    email: 'priya.singh@airport.gov.in',
    department: 'IT',
    role: 'Administrator',
    extension: '2458',
    location: 'Admin Block — Telecom Hub',
    deviceModel: 'Cisco IP Phone 8865',
    monthlyCalls: 112,
    monthlyCost: 520.15,
    status: 'Active',
    lastLogin: '2026-09-11 08:50:00',
  },
  {
    id: 'usr-5',
    name: 'Neha Verma',
    employeeId: 'EMP-FIN-10289',
    email: 'neha.verma@airport.gov.in',
    department: 'Finance',
    role: 'Billing Manager',
    extension: '2265',
    location: 'Admin Block — Accounts Wing',
    deviceModel: 'Cisco IP Phone 7841',
    monthlyCalls: 98,
    monthlyCost: 485.60,
    status: 'Active',
    lastLogin: '2026-09-10 16:20:00',
  },
  {
    id: 'usr-6',
    name: 'Arjun Mehta',
    employeeId: 'EMP-ENG-10310',
    email: 'arjun.mehta@airport.gov.in',
    department: 'Engineering',
    role: 'Viewer',
    extension: '2310',
    location: 'Cargo Terminal — HVAC Central',
    deviceModel: 'Cisco IP Phone 7821',
    monthlyCalls: 84,
    monthlyCost: 390.80,
    status: 'Active',
    lastLogin: '2026-09-10 14:10:00',
  },
  {
    id: 'usr-7',
    name: 'Kavita Rao',
    employeeId: 'EMP-OPS-10325',
    email: 'kavita.rao@airport.gov.in',
    department: 'Airport Operations',
    role: 'Viewer',
    extension: '2452',
    location: 'Terminal 3 — Apron Control',
    deviceModel: 'Cisco IP Phone 8845',
    monthlyCalls: 135,
    monthlyCost: 680.25,
    status: 'Active',
    lastLogin: '2026-09-11 07:40:00',
  },
  {
    id: 'usr-8',
    name: 'Suresh Yadav',
    employeeId: 'EMP-SEC-10340',
    email: 'suresh.yadav@airport.gov.in',
    department: 'Security',
    role: 'Viewer',
    extension: '2234',
    location: 'Terminal 2 — Perimeter Gate 3',
    deviceModel: 'Cisco IP Phone 7821',
    monthlyCalls: 94,
    monthlyCost: 410.50,
    status: 'Active',
    lastLogin: '2026-09-09 18:30:00',
  },
  {
    id: 'usr-9',
    name: 'Vikram Joshi',
    employeeId: 'EMP-OPS-10355',
    email: 'vikram.joshi@airport.gov.in',
    department: 'Airport Operations',
    role: 'Viewer',
    extension: '2455',
    location: 'Terminal 2 — Duty Manager',
    deviceModel: 'Cisco IP Phone 8845',
    monthlyCalls: 118,
    monthlyCost: 590.00,
    status: 'Active',
    lastLogin: '2026-09-10 11:20:00',
  },
  {
    id: 'usr-10',
    name: 'Rakesh Nair',
    employeeId: 'EMP-IT-10370',
    email: 'rakesh.nair@airport.gov.in',
    department: 'IT',
    role: 'Administrator',
    extension: '2460',
    location: 'Admin Block — Server Room',
    deviceModel: 'Cisco IP Phone 8865',
    monthlyCalls: 104,
    monthlyCost: 512.30,
    status: 'Active',
    lastLogin: '2026-09-11 11:00:00',
  },
  {
    id: 'usr-11',
    name: 'Deepak Shah',
    employeeId: 'EMP-ENG-10385',
    email: 'deepak.shah@airport.gov.in',
    department: 'Engineering',
    role: 'Viewer',
    extension: '2312',
    location: 'Terminal 3 — Power Substation',
    deviceModel: 'Cisco IP Phone 7821',
    monthlyCalls: 76,
    monthlyCost: 345.90,
    status: 'Active',
    lastLogin: '2026-09-08 15:45:00',
  },
  {
    id: 'usr-12',
    name: 'Ananya Iyer',
    employeeId: 'EMP-FIN-10400',
    email: 'ananya.iyer@airport.gov.in',
    department: 'Finance',
    role: 'Billing Manager',
    extension: '2268',
    location: 'Admin Block — Audit Cell',
    deviceModel: 'Cisco IP Phone 7841',
    monthlyCalls: 88,
    monthlyCost: 430.75,
    status: 'Active',
    lastLogin: '2026-09-10 13:15:00',
  },
  {
    id: 'usr-13',
    name: 'Meera Kapoor',
    employeeId: 'EMP-ADM-10415',
    email: 'meera.kapoor@airport.gov.in',
    department: 'Administration',
    role: 'Department Manager',
    extension: '2501',
    location: 'Terminal 1 — Director Secretariat',
    deviceModel: 'Cisco IP Phone 8865',
    monthlyCalls: 162,
    monthlyCost: 815.40,
    status: 'Active',
    lastLogin: '2026-09-11 10:10:00',
  },
  {
    id: 'usr-14',
    name: 'Sunil Menon',
    employeeId: 'EMP-TM-10430',
    email: 'sunil.menon@airport.gov.in',
    department: 'Terminal Management',
    role: 'Department Manager',
    extension: '2510',
    location: 'Terminal 3 — Concourse B',
    deviceModel: 'Cisco IP Phone 8845',
    monthlyCalls: 140,
    monthlyCost: 710.20,
    status: 'Active',
    lastLogin: '2026-09-11 09:15:00',
  },
  {
    id: 'usr-15',
    name: 'Pooja Hegde',
    employeeId: 'EMP-CS-10445',
    email: 'pooja.hegde@airport.gov.in',
    department: 'Passenger Services',
    role: 'Viewer',
    extension: '2525',
    location: 'Terminal 1 — Info Helpdesk',
    deviceModel: 'Cisco IP Phone 7841',
    monthlyCalls: 215,
    monthlyCost: 980.60,
    status: 'Active',
    lastLogin: '2026-09-11 11:20:00',
  },
  {
    id: 'usr-16',
    name: 'Rajesh Khanna',
    employeeId: 'EMP-CRG-10460',
    email: 'rajesh.khanna@airport.gov.in',
    department: 'Ground Handling',
    role: 'Viewer',
    extension: '2540',
    location: 'Cargo Terminal — Bay 8',
    deviceModel: 'Cisco IP Phone 7821',
    monthlyCalls: 110,
    monthlyCost: 530.40,
    status: 'Active',
    lastLogin: '2026-09-09 14:00:00',
  },
  {
    id: 'usr-17',
    name: 'Manoj Tiwari',
    employeeId: 'EMP-BAG-10475',
    email: 'manoj.tiwari@airport.gov.in',
    department: 'Facility Management',
    role: 'Viewer',
    extension: '2555',
    location: 'Terminal 2 — Baggage Make-Up Area',
    deviceModel: 'Cisco IP Phone 7821',
    monthlyCalls: 82,
    monthlyCost: 375.00,
    status: 'Active',
    lastLogin: '2026-09-10 17:50:00',
  },
  {
    id: 'usr-18',
    name: 'Harish Choudhury',
    employeeId: 'EMP-FAC-10490',
    email: 'harish.c@airport.gov.in',
    department: 'Facility Management',
    role: 'Viewer',
    extension: '2570',
    location: 'Terminal 1 — Utilities Center',
    deviceModel: 'Cisco IP Phone 7821',
    monthlyCalls: 65,
    monthlyCost: 295.50,
    status: 'Inactive',
    lastLogin: '2026-08-25 12:00:00',
  },
  {
    id: 'usr-19',
    name: 'Tanvi Saxena',
    employeeId: 'EMP-CS-10505',
    email: 'tanvi.saxena@airport.gov.in',
    department: 'Passenger Services',
    role: 'Viewer',
    extension: '2585',
    location: 'Terminal 2 — VIP Lounge Desk',
    deviceModel: 'Cisco IP Phone 7841',
    monthlyCalls: 175,
    monthlyCost: 840.10,
    status: 'Active',
    lastLogin: '2026-09-11 08:30:00',
  },
  {
    id: 'usr-20',
    name: 'Dinesh Karthik',
    employeeId: 'EMP-OPS-10520',
    email: 'dinesh.k@airport.gov.in',
    department: 'Airport Operations',
    role: 'Viewer',
    extension: '2600',
    location: 'Terminal 1 — Airside Ops',
    deviceModel: 'Cisco IP Phone 8845',
    monthlyCalls: 128,
    monthlyCost: 645.00,
    status: 'Active',
    lastLogin: '2026-09-10 19:10:00',
  },
];

export const mockSettings: SystemSettings = {
  organizationName: 'Airport Authority Telecom Wing',
  airportCode: 'DEL / VIDP',
  currency: 'INR',
  currencySymbol: '₹',
  timeZone: 'Asia/Kolkata (IST +05:30)',
  defaultTaxRate: 18,
  billingCycleDay: 1,
  gracePeriodDays: 20,
  roundingRule: 'CeilToMinute',
  cdrRetentionDays: 365,
  autoProcessIntervalMinutes: 5,
  duplicateRecordHandling: 'FlagForReview',
  emailAlertsEnabled: true,
  contactEmail: 'telecom.billing@airport.gov.in',
  contactPhone: '+91 11 2565 6000',
};
