import React from 'react';
import {
  AlertTriangle,
  CheckCircle2,
  Clock,
  Coins,
  FileSpreadsheet,
  PhoneCall,
} from 'lucide-react';
import { formatCurrency } from '../../../../utils/billingCalculator';
import type { CDRSummaryKPIs } from '../types';

interface CDRHeaderProps {
  kpis: CDRSummaryKPIs;
  totalRecordsCount: number;
  filteredCount: number;
  selectedCount: number;
}

export const CDRHeader: React.FC<CDRHeaderProps> = ({
  kpis,
  totalRecordsCount,
  filteredCount,
  selectedCount,
}) => {
  return (
    <div className="space-y-4">
      {/* Title & Badge */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white p-5 rounded-2xl border border-slate-200/90 shadow-xs">
        <div className="flex items-center space-x-3.5">
          <div className="w-11 h-11 rounded-xl bg-teal-600 flex items-center justify-center text-white shadow-xs">
            <PhoneCall className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-lg font-bold text-slate-900 tracking-tight">
                CDR Records
              </h1>
              <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-teal-100 text-teal-800">
                Transaction Level
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-0.5">
              View and analyze individual Call Detail Records generated by the airport telephone system.
            </p>
          </div>
        </div>

        {/* Live Counters */}
        <div className="flex items-center gap-2 text-xs font-mono self-start sm:self-auto bg-slate-50 p-1.5 rounded-xl border border-slate-200/80">
          <div className="px-2.5 py-1 rounded-lg bg-white border border-slate-200 shadow-2xs">
            <span className="text-slate-400 text-[10px] block uppercase font-bold">Total</span>
            <span className="font-bold text-slate-900">{totalRecordsCount.toLocaleString()}</span>
          </div>
          <div className="px-2.5 py-1 rounded-lg bg-white border border-slate-200 shadow-2xs">
            <span className="text-slate-400 text-[10px] block uppercase font-bold">Filtered</span>
            <span className="font-bold text-teal-700">{filteredCount.toLocaleString()}</span>
          </div>
          <div className="px-2.5 py-1 rounded-lg bg-white border border-slate-200 shadow-2xs">
            <span className="text-slate-400 text-[10px] block uppercase font-bold">Selected</span>
            <span className="font-bold text-slate-900">{selectedCount.toLocaleString()}</span>
          </div>
        </div>
      </div>

      {/* KPI Cards Row */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
        {/* Total Records */}
        <div className="bg-white p-4 rounded-2xl border border-slate-200/90 shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-[10px] uppercase font-bold text-slate-400">Total CDR Records</span>
            <FileSpreadsheet className="w-4 h-4 text-teal-600" />
          </div>
          <p className="text-xl font-bold font-mono text-slate-900 mt-1">
            {kpis.totalRecords.toLocaleString()}
          </p>
        </div>

        {/* Completed */}
        <div className="bg-white p-4 rounded-2xl border border-slate-200/90 shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-[10px] uppercase font-bold text-slate-400">Completed Calls</span>
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
          </div>
          <p className="text-xl font-bold font-mono text-emerald-700 mt-1">
            {kpis.completed.toLocaleString()}
          </p>
        </div>

        {/* Failed */}
        <div className="bg-white p-4 rounded-2xl border border-slate-200/90 shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-[10px] uppercase font-bold text-slate-400">Failed / Busy</span>
            <AlertTriangle className="w-4 h-4 text-rose-500" />
          </div>
          <p className="text-xl font-bold font-mono text-rose-700 mt-1">
            {kpis.failed.toLocaleString()}
          </p>
        </div>

        {/* Total Duration */}
        <div className="bg-white p-4 rounded-2xl border border-slate-200/90 shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-[10px] uppercase font-bold text-slate-400">Total Duration</span>
            <Clock className="w-4 h-4 text-teal-600" />
          </div>
          <p className="text-sm font-bold font-mono text-slate-800 mt-2 truncate">
            {kpis.totalDurationHours}
          </p>
        </div>

        {/* Total Billing */}
        <div className="bg-teal-50/70 p-4 rounded-2xl border border-teal-200 shadow-xs col-span-2 sm:col-span-1">
          <div className="flex items-center justify-between">
            <span className="text-[10px] uppercase font-bold text-teal-800">Total Telecom Invoiced</span>
            <Coins className="w-4 h-4 text-teal-700" />
          </div>
          <p className="text-xl font-extrabold font-mono text-teal-800 mt-1">
            {formatCurrency(kpis.totalBilling)}
          </p>
        </div>
      </div>
    </div>
  );
};
